artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/sgpjesus/bank-account-fraud-dataset-neurips-2022/
  local_data_file: 
  unzip_dir:
